steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Update staging server
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        gcloud compute ssh nikk@apps --zone=us-central1-a --command='/bin/sh /home/nikk/pull.sh'
